src/Entity/Membre.php
<?php

namespace App\Entity;

use App\Repository\MembreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: MembreRepository::class)]
#[UniqueEntity(fields: ['pseudo'], message: 'There is already an account with this pseudo')]
class Membre implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $pseudo = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 20)]
    private ?string $nom = null;

    #[ORM\Column(length: 20)]
    private ?string $prenom = null;

    #[ORM\Column(length: 50)]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    private ?string $civilite = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_enregistrement = null;

    #[ORM\OneToMany(mappedBy: 'membres', targetEntity: Commande::class)]
    private Collection $commandes;

    public function __construct()
    {
        $this->commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->pseudo;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->pseudo;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getCivilite(): ?string
    {
        return $this->civilite;
    }

    public function setCivilite(string $civilite): self
    {
        $this->civilite = $civilite;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $date_enregistrement): self
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes->add($commande);
            $commande->setMembres($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getMembres() === $this) {
                $commande->setMembres(null);
            }
        }

        return $this;
    }
    public function __toString(): string
    {
        return $this->getPseudo() ;
    }

}

src/Controller/ShopController.php
<?php

namespace App\Controller;

use App\Entity\Produit;
use App\Repository\ProduitRepository;
use App\Repository\CommandeRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use SebastianBergmann\CodeCoverage\Report\Html\Renderer;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ShopController extends AbstractController
{
    #[Route('/', name: 'app_shop')]
    public function index(ProduitRepository $repo): Response
    {
        $produit=$repo->findAll();
        return $this->render('shop/index.html.twig', [
            'Produits' => $produit
        ]);
        return $this->render('shop/index.html.twig', [
            'controller_name' => 'ShopController',
        ]);
    }
    #[Route('/profil/{id}', name:"app_profil")]
        public function profil(CommandeRepository $repo )
        {
            
            $commande = $repo->findAll();


            return$this->render('shop/profil.html.twig', [
                'commandes'=>$commande
            ]);
        }

    
}

templates/shop/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ShopController!{% endblock %}

{% block body %}
<div class="example-wrapper">
    <h1>Hey You  </h1>
    Amuse toi et claque un max de fric 
    </div>

    <section class="row articles">
    
    {% for produit in Produits %}
        
             {% if produit.stock > 0 %}
        
        <div class="card col-md-3 m-3 p-2" >
            <img class="img-fluid" src="{{produit.photo}}" alt="">
            <div >
                <h5 class="card-title">{{produit.titre}}</h5>
                <div class="metadata">
                Couleur: {{ produit.couleur }}
                <br>
                Taille: {{ produit.taille }}
                <br>
                Prix: {{ produit.prix }}€
                <br>
                {{ produit.stock }}
                Publié le 
                 {{produit.DateEnregistrement|date('d/m/Y à H:i:s')}}
                </div>
                <p class="card-text">{{ produit.description|raw}}</p>
                 <a href="{{ path('cart_add', {id:produit.id}) }}" class="btn btn-primary">Ajouter au Panier</a>  
            </div>
        </div>
       {% endif %}
     {% endfor %}
    </section>
{% endblock %}

templates/shop/profil.html.twig
{% extends 'base.html.twig' %}

{% block title %} Profil {% endblock %}

{% block body %}
        <h1>Mon profil</h1>

           <th scope="row"></th>
            <h5 class="card-header">{{app.user.pseudo}}, Vos informations:</h5>
            <div class="metadata">
            <br>
            <p class="card-text">Nom: {{app.user.nom}}</p>
            <br>
            <p class="card-text">Prenom: {{app.user.prenom}}</p>
            <br>
            <p class="card-text">Email: {{app.user.Email}}</p>
            <br>
            <p class="card-text">Civilite: {{app.user.civilite}}</p>
            <br>
            <a href="{{ path('app_login') }}" class="btn btn-success">Gérer mon profil</a>
            <br>
            <br>    

        <h2>Mes commandes</h2>
    {% for commande in commandes %}
    {# {% if commande.membres == app.user.id %} #}
    <div class="card border-success mb-3" style="max-width: 80vw;">
            <div class="card-header"><h3>Commande du {{commande.dateEnregistrement|date("d/m/y à H:i:s")}}</h3></div>
            <div class="card-body">
                <h4 class="card-title">{{commande.produits.titre}}</h4>
                
                <p class="card-text">
                T'en as commandé : {{commande.quantite}}
                <br>
                Ta commande est : {{commande.etat}}
                <h5>Prix Total : {{ commande.montant }}€</h5>               
                </p>
            </div>
        </div>

    {# {% endif %} #}
        
    {% endfor %}
   
    

{% endblock %}